// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpfrmclsraiidjlfeonj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwZnJtY2xzcmFpaWRqbGZlb25qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Mjc0OTAsImV4cCI6MjA2NDIwMzQ5MH0.jlQsHLPhJVRx_TIiGJZhXFsFL4I-7EtRLtIA5H1t8rM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});